fun main() {
    println("--- Lista de Empleados ---")
    println("Inmutable")
    val empleados = listOf("Ana López", "Luis Vera", "Carmen Ruiz", "Pedro Salas", "Sofía Paz")
    println(empleados)
    println("Cantidad: ${empleados.size}")
    println("Primero: ${empleados[0]}")
    println("Primer elemento: ${empleados.first()}")
    println("Último: ${empleados.last()}")
    println("Índice 2: ${empleados.get(2)}")
    println("Índice de Luis: ${empleados.indexOf("Luis Vera")}")
    println("Contiene a Ana? ${empleados.contains("Ana López")}")
    println("Carlos está? ${"Carlos" in empleados}")

    println("Sub-lista (1-3): ${empleados.subList(1, 4)}")
    println("Primeros 2: ${empleados.take(2)}")
    println("Saltar 3: ${empleados.drop(3)}")
    println("Últimos 2: ${empleados.takeLast(2)}")

    println("Mutable")
    val cargos = mutableListOf("Contador", "Analista RRHH", "Desarrollador", "Vendedor")
    println(cargos)
    cargos.add("Supervisor")
    println(cargos)
    cargos.add(1, "Asistente")
    println(cargos)
    cargos.remove("Vendedor")
    println(cargos)
    cargos[1] = "Coordinador"
    println(cargos)

    println("ArrayDeque - Últimas contrataciones")
    val ultimos = ArrayDeque<String>()
    ultimos.addFirst("Juan")
    println(ultimos)
    ultimos.addFirst("María")
    println(ultimos)
    ultimos.addLast("Pedro")
    println(ultimos)
    ultimos.removeFirst()
    println(ultimos)
    ultimos.removeLast()
    println(ultimos)
}
