fun main() {
 println("Set")
 println("Inmutables")
 val numeros=setOf(1,2,3,4,5,3,4,2,1,1,3)
 println(numeros)
 println("Operaciones de conjuntos")
 val pares=setOf(2,4,6,8,10)
 println("Pares $pares")
 val impares=setOf(1,3,5,7,9)
 val multiplos3=setOf(3,6,9,12)
 println("Impares $impares")
 println("Union ${impares union pares}")
 println("Interseccion ${multiplos3 intersect pares}")
 println("Substraccion ${impares subtract pares}")
 println("Pares $pares")
 println("Impares $impares")
 
 println("Set")
 println("Mutables")
 val lenguajes = mutableSetOf("Kotlin", "Java", "Reactnative")
 println(lenguajes)
 lenguajes.add("Javascript")
 println(lenguajes)
 lenguajes.add("kotlin")
 println(lenguajes)
 lenguajes.remove("Java")
 println(lenguajes)
 println("Verificar si un valor existe ${"kotlin" in lenguajes}")
 println("Verificar si un valor existe ${"java" in lenguajes}")
}